# Generated by Django 5.1.6 on 2025-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emotion', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
